---
title: "ADA Midterm exam"
author: "Guhan Iyer"
date: "10/17/2021"
output: html_document
---


```{r}
# Import dataset from Github
library(readr)

brfss <- read_csv("https://raw.githubusercontent.com/kijohnson/ADA-Fall-2021/master/BRFSS2017_10percent_v.csv")

# check class of variables and confirm

sapply(brfss, class)

# Sex is a numeric variable in this dataset, so first we should convert it to a character variable

brfss$sexrecode <- ifelse(brfss$SEX == 1, "Male", ifelse(brfss$SEX == 2, "Female", ifelse(brfss$SEX == 9, "Not Specified", NA))) # code creates a new character variable for sex

# Calculate median height by sex

library(tidyverse) # contains dplyr and ggplot, useful for descriptives and data visualization

brfss %>%  # specify dataset
  group_by(sexrecode) %>%  # specifies grouping variable, in this case sex
  summarise(median(ht_meters, na.rm = TRUE))  # specifies dependent variable, in this case height in meters, and removes NA values

boxplot1 <- ggplot(data = brfss, aes(x = sexrecode, y = ht_meters)) + # ggplot specifies data, x and y variables
  geom_boxplot(aes(color = sexrecode)) + # geom_boxplot says that the visual should be a boxplot, aes gives color by sex
  labs(x = "Sex", y = "Height (m)", title = "Height by Sex") + # labs changes labels for title, x and y axes
  theme(legend.position = "None") # remove legend from plot


boxplot1 # display boxplot1. This boxplot has a group for not specified. We can clean this up by creating a new dataframe that only includes observations that are either male or female. Be sure to make a NEW dataframe if you want to keep the data from the "not specified" observations for some other reason.


brfss1 <- brfss[brfss$sexrecode != "Not Specified",] # creates a new dataframe that includes all observations except those that responded "Not Specified" for the sexrecode variable

# create a new boxplot with the new dataframe
ggplot(data = brfss1, aes(x = sexrecode, y = ht_meters)) + 
  geom_boxplot(aes(color = sexrecode)) +
  labs(x = "Sex", y = "Height (m)", title = "Height by Sex") +
  theme(legend.position = "None")

# to determine the mean height for each sex, we can use similar code that we used to calculate the median

brfss %>% 
  group_by(sexrecode) %>% 
  summarise(mean(ht_meters, na.rm = TRUE)) # mean instead of median

```

```{r}

sapply(brfss, class)

brfss$sexrecodeMF <- brfss$sexrecode

sapply(brfss, class)

brfss1 <- brfss[brfss$sexrecodeMF != "Not Specified",]

ggplot(data = brfss1, aes(x = sexrecodeMF, y = ht_meters)) + 
  geom_boxplot(aes(color = sexrecodeMF)) +
  labs(x = "Sex", y = "Height (m)", title = "Height by Sex") +
  theme(legend.position = "None")




```